# Artificer · Dark — gum style environment
# gum has no config file (charmbracelet/gum#991). Source this fragment from a
# shell rc, or from a script that calls gum outside an interactive shell.
#
# Generated from themes/_palette.json — edit there + re-run build.mjs.
# Every value is a hex; gum needs a truecolor-capable terminal to render them
# exactly, and degrades to the nearest 256 colour otherwise.

# gum choose
export GUM_CHOOSE_CURSOR_FOREGROUND="#dbbb6f"
export GUM_CHOOSE_CURSOR_BACKGROUND=""
export GUM_CHOOSE_HEADER_FOREGROUND="#c5c8c6"
export GUM_CHOOSE_HEADER_BACKGROUND=""
export GUM_CHOOSE_ITEM_FOREGROUND="#e8e6e1"
export GUM_CHOOSE_ITEM_BACKGROUND=""
export GUM_CHOOSE_SELECTED_FOREGROUND="#e3c885"
export GUM_CHOOSE_SELECTED_BACKGROUND=""

# gum confirm
export GUM_CONFIRM_PROMPT_FOREGROUND="#e8e6e1"
export GUM_CONFIRM_PROMPT_BACKGROUND=""
export GUM_CONFIRM_SELECTED_FOREGROUND="#292c33"
export GUM_CONFIRM_SELECTED_BACKGROUND="#dbbb6f"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#c5c8c6"
export GUM_CONFIRM_UNSELECTED_BACKGROUND=""

# gum file
export GUM_FILE_CURSOR_FOREGROUND="#dbbb6f"
export GUM_FILE_CURSOR_BACKGROUND=""
export GUM_FILE_DIRECTORY_FOREGROUND="#7da6a4"
export GUM_FILE_DIRECTORY_BACKGROUND=""
export GUM_FILE_FILE_FOREGROUND="#e8e6e1"
export GUM_FILE_FILE_BACKGROUND=""
export GUM_FILE_FILE_SIZE_FOREGROUND="#5a7a8a"
export GUM_FILE_FILE_SIZE_BACKGROUND=""
export GUM_FILE_HEADER_FOREGROUND="#c5c8c6"
export GUM_FILE_HEADER_BACKGROUND=""
export GUM_FILE_PERMISSIONS_FOREGROUND="#5a7a8a"
export GUM_FILE_PERMISSIONS_BACKGROUND=""
export GUM_FILE_SELECTED_FOREGROUND="#e3c885"
export GUM_FILE_SELECTED_BACKGROUND=""
export GUM_FILE_SYMLINK_FOREGROUND="#b095e0"
export GUM_FILE_SYMLINK_BACKGROUND=""

# gum filter
export GUM_FILTER_CURSOR_TEXT_FOREGROUND="#dbbb6f"
export GUM_FILTER_CURSOR_TEXT_BACKGROUND=""
export GUM_FILTER_HEADER_FOREGROUND="#c5c8c6"
export GUM_FILTER_HEADER_BACKGROUND=""
export GUM_FILTER_INDICATOR_FOREGROUND="#dbbb6f"
export GUM_FILTER_INDICATOR_BACKGROUND=""
export GUM_FILTER_MATCH_FOREGROUND="#e3c885"
export GUM_FILTER_MATCH_BACKGROUND=""
export GUM_FILTER_PLACEHOLDER_FOREGROUND="#5a7a8a"
export GUM_FILTER_PLACEHOLDER_BACKGROUND=""
export GUM_FILTER_PROMPT_FOREGROUND="#dbbb6f"
export GUM_FILTER_PROMPT_BACKGROUND=""
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#dbbb6f"
export GUM_FILTER_SELECTED_PREFIX_BACKGROUND=""
export GUM_FILTER_TEXT_FOREGROUND="#e8e6e1"
export GUM_FILTER_TEXT_BACKGROUND=""
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#5a7a8a"
export GUM_FILTER_UNSELECTED_PREFIX_BACKGROUND=""

# gum input
export GUM_INPUT_CURSOR_FOREGROUND="#dbbb6f"
export GUM_INPUT_CURSOR_BACKGROUND=""
export GUM_INPUT_HEADER_FOREGROUND="#c5c8c6"
export GUM_INPUT_HEADER_BACKGROUND=""
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#5a7a8a"
export GUM_INPUT_PLACEHOLDER_BACKGROUND=""
export GUM_INPUT_PROMPT_FOREGROUND="#dbbb6f"
export GUM_INPUT_PROMPT_BACKGROUND=""

# gum log
export GUM_LOG_KEY_FOREGROUND="#e3c885"
export GUM_LOG_KEY_BACKGROUND=""
export GUM_LOG_LEVEL_FOREGROUND="#c4808a"
export GUM_LOG_LEVEL_BACKGROUND=""
export GUM_LOG_MESSAGE_FOREGROUND="#e8e6e1"
export GUM_LOG_MESSAGE_BACKGROUND=""
export GUM_LOG_PREFIX_FOREGROUND="#c5c8c6"
export GUM_LOG_PREFIX_BACKGROUND=""
export GUM_LOG_SEPARATOR_FOREGROUND="#5a7a8a"
export GUM_LOG_SEPARATOR_BACKGROUND=""
export GUM_LOG_TIME_FOREGROUND="#5a7a8a"
export GUM_LOG_TIME_BACKGROUND=""
export GUM_LOG_VALUE_FOREGROUND="#e8e6e1"
export GUM_LOG_VALUE_BACKGROUND=""

# gum pager
export GUM_PAGER_FOREGROUND="#e8e6e1"
export GUM_PAGER_BACKGROUND=""
export GUM_PAGER_HELP_FOREGROUND="#5a7a8a"
export GUM_PAGER_HELP_BACKGROUND=""
export GUM_PAGER_LINE_NUMBER_FOREGROUND="#5a7a8a"
export GUM_PAGER_LINE_NUMBER_BACKGROUND=""
export GUM_PAGER_MATCH_FOREGROUND="#e3c885"
export GUM_PAGER_MATCH_BACKGROUND=""
export GUM_PAGER_MATCH_HIGH_FOREGROUND="#292c33"
export GUM_PAGER_MATCH_HIGH_BACKGROUND="#dbbb6f"

# gum spin
export GUM_SPIN_SPINNER_FOREGROUND="#dbbb6f"
export GUM_SPIN_SPINNER_BACKGROUND=""
export GUM_SPIN_TITLE_FOREGROUND="#e8e6e1"
export GUM_SPIN_TITLE_BACKGROUND=""

# gum table
export GUM_TABLE_BORDER_FOREGROUND="#4a4f5c"
export GUM_TABLE_BORDER_BACKGROUND=""
export GUM_TABLE_CELL_FOREGROUND="#e8e6e1"
export GUM_TABLE_CELL_BACKGROUND=""
export GUM_TABLE_HEADER_FOREGROUND="#e3c885"
export GUM_TABLE_HEADER_BACKGROUND=""
export GUM_TABLE_SELECTED_FOREGROUND="#292c33"
export GUM_TABLE_SELECTED_BACKGROUND="#dbbb6f"

# gum write
export GUM_WRITE_BASE_FOREGROUND="#e8e6e1"
export GUM_WRITE_BASE_BACKGROUND=""
export GUM_WRITE_CURSOR_FOREGROUND="#dbbb6f"
export GUM_WRITE_CURSOR_BACKGROUND=""
export GUM_WRITE_CURSOR_LINE_FOREGROUND="#e8e6e1"
export GUM_WRITE_CURSOR_LINE_BACKGROUND=""
export GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND="#dbbb6f"
export GUM_WRITE_CURSOR_LINE_NUMBER_BACKGROUND=""
export GUM_WRITE_END_OF_BUFFER_FOREGROUND="#5a7a8a"
export GUM_WRITE_END_OF_BUFFER_BACKGROUND=""
export GUM_WRITE_HEADER_FOREGROUND="#c5c8c6"
export GUM_WRITE_HEADER_BACKGROUND=""
export GUM_WRITE_LINE_NUMBER_FOREGROUND="#5a7a8a"
export GUM_WRITE_LINE_NUMBER_BACKGROUND=""
export GUM_WRITE_PLACEHOLDER_FOREGROUND="#5a7a8a"
export GUM_WRITE_PLACEHOLDER_BACKGROUND=""
export GUM_WRITE_PROMPT_FOREGROUND="#dbbb6f"
export GUM_WRITE_PROMPT_BACKGROUND=""
