#!/usr/bin/env node
// Artificer · Subresource Integrity (SRI) generator
// Computes sha384 integrity hashes for the CDN-served src/ files and writes:
//   - dist-meta/integrity.json   machine-readable {version, algorithm, files}
//   - dist-meta/cdn-snippet.html copy-pasteable <link>/<script integrity=…> block
// Also prints the snippet to stdout.
//
// Why sha384: the SRI-recommended algorithm — strong, and shorter base64 than
// sha512. jsDelivr serves the published npm package, so a pinned URL +
// integrity hash means a tampered CDN response fails to load instead of
// running. Hashes are content-derived, so output is stable for a given commit.
//
// Usage:  node scripts/gen-sri.mjs   (or: npm run sri)
// Output is generated/ephemeral — regenerated per release in CI. Gitignored.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const ALGO = 'sha384';
const PKG = '@cameronsjo/artificer';
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

// CDN-served subresources, in the order a consumer would wire them. Paths are
// relative to the package root (the npm tarball ships `src/`). tokens.json is
// fetched, not tagged, so it gets a manifest entry but no HTML element.
const FILES = [
  { path: 'src/artificer.css',           kind: 'css' },
  { path: 'src/print.css',               kind: 'css' },
  { path: 'src/artificer-whimsy.css',    kind: 'css' },
  { path: 'src/artificer-editorial.css', kind: 'css' },
  { path: 'src/artificer-theme.js',   kind: 'js' },
  { path: 'src/artificer-focus.js',   kind: 'js' },
  { path: 'src/artificer-icons.js',   kind: 'js' },
  { path: 'src/artificer-whimsy.js',  kind: 'js' },
  { path: 'src/tokens.json',          kind: 'json' },
];

const integrity = (relPath) => {
  const buf = readFileSync(join(root, relPath));
  const digest = createHash(ALGO).update(buf).digest('base64');
  return `${ALGO}-${digest}`;
};

const cdnUrl = (relPath) =>
  `https://cdn.jsdelivr.net/npm/${PKG}@${version}/${relPath}`;

const files = {};
for (const { path } of FILES) files[path] = integrity(path);

const manifest = { package: PKG, version, algorithm: ALGO, files };

// HTML snippet: <link> for CSS, <script defer> for JS. tokens.json omitted —
// it has no subresource tag (use the integrity hash with fetch() if needed).
const snippetLines = FILES.filter((f) => f.kind !== 'json').map(({ path, kind }) => {
  const url = cdnUrl(path);
  return kind === 'css'
    ? `<link rel="stylesheet" href="${url}" integrity="${files[path]}" crossorigin="anonymous" />`
    : `<script src="${url}" integrity="${files[path]}" crossorigin="anonymous" defer></script>`;
});

const snippet = [
  `<!-- Artificer ${PKG}@${version} — pinned CDN + SRI. Generated by scripts/gen-sri.mjs. -->`,
  ...snippetLines,
  '',
].join('\n');

const outDir = join(root, 'dist-meta');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'integrity.json'), JSON.stringify(manifest, null, 2) + '\n');
writeFileSync(join(outDir, 'cdn-snippet.html'), snippet);

console.log(snippet);
console.error(`wrote dist-meta/integrity.json + dist-meta/cdn-snippet.html (v${version})`);
