#!/usr/bin/env node
// Artificer · Subresource Integrity (SRI) generator
// Computes sha384 integrity hashes for the CDN-served src/ files and writes:
//   - dist-meta/integrity.json   machine-readable {version, algorithm, files}
//   - dist-meta/cdn-snippet.html copy-pasteable <link>/<script integrity=…> block
// Also prints the snippet to stdout.
//
// Why sha384: the SRI-recommended algorithm — strong, and shorter base64 than
// sha512. jsDelivr serves the published npm package, so a pinned URL +
// integrity hash means a tampered CDN response fails to load instead of
// running. Hashes are content-derived, so output is stable for a given commit.
//
// Usage:  node scripts/gen-sri.mjs   (or: npm run sri)
// Output is generated/ephemeral — regenerated per release in CI. Gitignored.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const ALGO = 'sha384';
const PKG = '@cameronsjo/artificer';
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const { version } = pkg;

// CDN-served subresources, DERIVED from package.json `exports` so a future
// module cannot be silently omitted (issue 205 — the behavior modules shipped
// with no SRI entry while this was a hand-maintained list). Exports order is
// wire order: stylesheets first, then behavior modules, then tokens.json
// (fetched, not tagged — manifest entry, no HTML element). `./package.json`
// is the package's own manifest, not a CDN subresource. Kind comes from the
// extension; an export with an unknown extension fails loudly rather than
// shipping untagged.
const KIND = { '.css': 'css', '.js': 'js', '.json': 'json' };
const FILES = [...new Set(
  Object.entries(pkg.exports)
    // `./package.json` is the package's own manifest; `./react` is the
    // compiled ESM adapter — imported by bundlers, never CDN-script-tagged,
    // so it gets no SRI entry by design. Conditional exports ({types,
    // default}) resolve to their runtime `default` target.
    .filter(([name]) => name !== './package.json' && name !== './react')
    .map(([, target]) => (typeof target === 'string' ? target : target.default)),
)].map((target) => {
  const path = target.replace(/^\.\//, '');
  const kind = KIND[extname(path)];
  if (!kind) throw new Error(`gen-sri: no kind for export "${target}" — extend KIND`);
  return { path, kind };
});

const integrity = (relPath) => {
  const buf = readFileSync(join(root, relPath));
  const digest = createHash(ALGO).update(buf).digest('base64');
  return `${ALGO}-${digest}`;
};

const cdnUrl = (relPath) =>
  `https://cdn.jsdelivr.net/npm/${PKG}@${version}/${relPath}`;

export function generateSriArtifacts() {
  const files = {};
  for (const { path } of FILES) files[path] = integrity(path);

  const manifest = { package: PKG, version, algorithm: ALGO, files };

  // HTML snippet: <link> for CSS, <script defer> for JS. tokens.json omitted —
  // it has no subresource tag (use the integrity hash with fetch() if needed).
  const snippetLines = FILES.filter((f) => f.kind !== 'json').map(({ path, kind }) => {
    const url = cdnUrl(path);
    return kind === 'css'
      ? `<link rel="stylesheet" href="${url}" integrity="${files[path]}" crossorigin="anonymous" />`
      : `<script src="${url}" integrity="${files[path]}" crossorigin="anonymous" defer></script>`;
  });

  const snippet = [
    `<!-- Artificer ${PKG}@${version} — pinned CDN + SRI. Generated by scripts/gen-sri.mjs. -->`,
    ...snippetLines,
    '',
  ].join('\n');

  const outDir = join(root, 'dist-meta');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'integrity.json'), JSON.stringify(manifest, null, 2) + '\n');
  writeFileSync(join(outDir, 'cdn-snippet.html'), snippet);

  return { manifest, snippet };
}

// Direct execution only (same guard as lint-css-tokens.mjs) — importing this
// module must not touch the filesystem or log.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { snippet } = generateSriArtifacts();
  console.log(snippet);
  console.error(`wrote dist-meta/integrity.json + dist-meta/cdn-snippet.html (v${version})`);
}
